pipeline {
    agent any

    tools {
        maven 'M3'  // This must match the Maven name configured in Jenkins
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                git url: 'https://github.com/YOGESHnp/edureka-retail-portal.git'
            }
        }

        stage('Build') {
            steps {
                dir('ABC Technologies') {
                    sh 'ls -l'
                    sh 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ABC Technologies') {
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('ABC Technologies') {
                    sh 'mvn package'
                }
            }
        }
    }
}
