pipeline {
    agent any

    tools {
        maven 'M3'  // Name should match the Maven installation under "Global Tool Configuration"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/YOGESHnp/edureka-retail-portal.git'
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
    }
}
